name: Update blog posts
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme-with-blog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://aiexponent.com/feed/"
          max_post_count: 5
          readme_path: "./README.md"
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          comment_tag_name: "BLOG-POST-LIST"
