name: Update blog posts
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          # Use r.jina.ai as a proxy to work around 403 errors from the origin
          feed_list: "https://r.jina.ai/https://aiexponent.com/feed"
          max_post_count: 5

